project:
  type: website
  output-dir: docs

website:
  title: ""
  navbar:
    left:
    - index.qmd
      

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    smooth-scroll: true
    toc: true
